import tkinter as tk
root = tk.Tk()
root.title("Tkinter Geometry Methods")
root.geometry("400x300")
frame1 = tk.Frame(root, bg="lightblue")
frame1.pack(fill="x")
tk.Label(frame1, text="PACK Method", bg="lightblue").pack(pady=5)
tk.Button(frame1, text="Button 1").pack(side="left", padx=10, pady=5)
tk.Button(frame1, text="Button 2").pack(side="left", padx=10, pady=5)
frame2 = tk.Frame(root, bg="lightgreen")
frame2.pack(pady=20)
tk.Label(frame2, text="GRID Method", bg="lightgreen").grid(row=0, column=0, columnspan=2)
tk.Button(frame2, text="Button 1").grid(row=1, column=0, padx=10, pady=10)
tk.Button(frame2, text="Button 2").grid(row=1, column=1, padx=10, pady=10)
tk.Label(root, text="PLACE Method", bg="lightyellow").place(x=130, y=200)
tk.Button(root, text="Button 1").place(x=100, y=230)
tk.Button(root, text="Button 2").place(x=200, y=230)
root.mainloop()
